version: '2'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd!
      MYSQL_DATABASE: yii
      MYSQL_USER: yii
      MYSQL_PASSWORD: Passw0rd!
  web:
    build: ./docker/php/
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/webapp/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    links:
      - db
    environment:
      WEB_DB_HOST: db
      WEB_DB_PORT: 3306
      WEB_DB_PASSWORD: Passw0rd!
      PHP_XDEBUG_IDEKEY: PHPSTORM
